export { PE_FILE } from "./node-pe-file";
export { IMAGE_DOS_HEADER } from "./IMAGE_DOS_HEADER";
export { IMAGE_NT_HEADERS } from "./IMAGE_NT_HEADERS";
export { IMAGE_FILE_HEADER } from "./IMAGE_FILE_HEADER";
export { IMAGE_OPTIONAL_HEADER } from "./IMAGE_OPTIONAL_HEADER";
export {
  IMAGE_SECTION_HEADER,
  IMAGE_SECTION_HEADER_MISC,
} from "./IMAGE_SECTION_HEADER";
export {
  CREATE_IMAGE_EXPORT_DIRECTORY,
  IMAGE_EXPORT_DIRECTORY,
  IMAGE_EXPORT_DIRECTORY_PARSE,
} from "./IMAGE_EXPORT_DIRECTORY";

export {
  CREATE_IMAGE_DIRECTORY_ENTRY_BASERELOC,
  IMAGE_DIRECTORY_ENTRY_BASERELOC,
  IMAGE_DIRECTORY_ENTRY_BASERELOC_PARSE,
} from "./IMAGE_DIRECTORY_ENTRY_BASERELOC";

export { Section_Flags } from "./flags";

export {
  BYTE_t,
  WORD_t,
  DWORD_t,
  QWORD_t,
  IMAGE_SIZEOF_SHORT_NAME_t,
  IMAGE_DIRECTORY_ENTRY_EXPORT_INDEX,
  IMAGE_DIRECTORY_ENTRY_IMPORT_INDEX,
  IMAGE_DIRECTORY_ENTRY_RESOURCE_INDEX,
  IMAGE_DIRECTORY_ENTRY_EXCEPTION_INDEX,
  IMAGE_DIRECTORY_ENTRY_SECURITY_INDEX,
  IMAGE_DIRECTORY_ENTRY_BASERELOC_INDEX,
  IMAGE_DIRECTORY_ENTRY_DEBUG_INDEX,
  IMAGE_DIRECTORY_ENTRY_COPYRIGHT_INDEX,
  IMAGE_DIRECTORY_ENTRY_GLOBALPTR_INDEX,
  IMAGE_DIRECTORY_ENTRY_TLS_INDEX,
  IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG_INDEX,
  IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT_INDEX,
  IMAGE_DIRECTORY_ENTRY_IAT_INDEX,
  IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT_INDEX,
  IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR_INDEX,
  IMAGE_DIRECTORY_ENTRY_NULL_INDEX,
} from "./types";

export { readByte, memcpy, copyBuffer, buffer2dec, buffer2hex } from "./tools";

export {
  RVA2FOA,
  mem2buffer,
  getSectionFlags,
  getFileHeaderCharacteristicsFlags,
  runPeFile,
  getPeFilesize,
  pushSection,
  align,
  isX64PE,
} from "./pe-tools";
