export { PE_FILE } from "./node-pe-file";
export { IMAGE_DOS_HEADER } from "./IMAGE_DOS_HEADER";
export { IMAGE_NT_HEADERS } from "./IMAGE_NT_HEADERS";
export { IMAGE_FILE_HEADER } from "./IMAGE_FILE_HEADER";
export { IMAGE_OPTIONAL_HEADER } from "./IMAGE_OPTIONAL_HEADER";
export {
  IMAGE_SECTION_HEADER,
  IMAGE_SECTION_HEADER_MISC,
} from "./IMAGE_SECTION_HEADER";

export { Section_Flags } from "./flags";

export {
  BYTE,
  WORD,
  DWORD,
  QWORD,
  IMAGE_SIZEOF_SHORT_NAME,
  IMAGE_DIRECTORY_ENTRY_EXPORT,
  IMAGE_DIRECTORY_ENTRY_IMPORT,
  IMAGE_DIRECTORY_ENTRY_RESOURCE,
  IMAGE_DIRECTORY_ENTRY_EXCEPTION,
  IMAGE_DIRECTORY_ENTRY_SECURITY,
  IMAGE_DIRECTORY_ENTRY_BASERELOC,
  IMAGE_DIRECTORY_ENTRY_DEBUG,
  IMAGE_DIRECTORY_ENTRY_COPYRIGHT,
  IMAGE_DIRECTORY_ENTRY_GLOBALPTR,
  IMAGE_DIRECTORY_ENTRY_TLS,
  IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG,
  IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT,
  IMAGE_DIRECTORY_ENTRY_IAT,
  IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT,
  IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR,
  IMAGE_DIRECTORY_ENTRY_NULL,
} from "./types";

export { readByte, memcpy, copyBuffer, buffer2dec, buffer2hex } from "./tools";

export {
  RVA2FOA,
  mem2buffer,
  getSectionFlags,
  runPeFile,
  getPeFilesize,
  pushSection,
  align,
  isX64PE
} from "./pe-tools";
